# Generated by Django 5.2 on 2025-07-16 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='급식을 제공하는 날짜', verbose_name='급식 날짜')),
                ('menu_content', models.TextField(help_text='점심 메뉴 내용을 입력하세요', verbose_name='점심 메뉴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '급식 메뉴',
                'verbose_name_plural': '급식 메뉴들',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
