# Generated by Django 5.2 on 2025-07-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchmenu',
            options={'ordering': ['-date', 'menu_type'], 'verbose_name': '급식 메뉴', 'verbose_name_plural': '급식 메뉴들'},
        ),
        migrations.AlterUniqueTogether(
            name='lunchmenu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='allergens',
            field=models.CharField(blank=True, help_text='알레르기 유발 요소 (예: 우유, 견과류 등)', max_length=200, verbose_name='알레르기 정보'),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='calories',
            field=models.IntegerField(blank=True, help_text='총 칼로리 (선택사항)', null=True, verbose_name='칼로리'),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='menu_type',
            field=models.CharField(choices=[('A', 'A식단'), ('B', 'B식단')], default='A', help_text='A식단 또는 B식단 선택', max_length=10, verbose_name='메뉴 타입'),
        ),
        migrations.AlterUniqueTogether(
            name='lunchmenu',
            unique_together={('date', 'menu_type')},
        ),
    ]
