# Generated by Django 5.2 on 2025-07-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchup', '0002_alter_lunchmenu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchmenu',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='lunchmenu',
            name='calories',
        ),
        migrations.AlterField(
            model_name='lunchmenu',
            name='menu_type',
            field=models.CharField(choices=[('normal', '일반식'), ('special', '특별식')], default='A', help_text='일반식단 또는 특별식단 선택', max_length=10, verbose_name='메뉴 타입'),
        ),
    ]
